#cloud-config
write_files:
- path: /tmp/k8s-cka.sh
  content: |
    #!/bin/bash
     
    #Prepare the network requirements.
    cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
    overlay
    br_netfilter
    EOF

    sudo modprobe overlay
    sudo modprobe br_netfilter

    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF

    sudo sysctl --system

    #Install and configure containerd.
    sudo apt-get update && sudo apt-get install -y containerd
    sudo mkdir -p /etc/containerd
    sudo containerd config default | sudo tee /etc/containerd/config.toml
    sudo systemctl restart containerd

    #Disable swap:
    sudo swapoff -a
    
    #Install kubeadm, kubelet, and kubectl version 1.20.0.
    sudo apt-get update && sudo apt-get install -y apt-transport-https curl

    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

    cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
    deb https://apt.kubernetes.io/ kubernetes-xenial main
    EOF

    sudo apt-get update && sudo apt-get dist-upgrade
    sudo apt-get install -y kubelet=1.20.0-00 kubeadm=1.20.0-00 kubectl=1.20.0-00
    sudo apt-mark hold kubelet kubeadm kubectl
    
    #Additional package for troubleshooting. 
    sudo apt install -y net-tools 

    #To keep the SSH session alive.
    sudo echo "ClientAliveInterval 60" >> /etc/ssh/sshd_config
    systemctl restart sshd

runcmd:
- ["sh", "/tmp/k8s-cka.sh"]
